# -*- coding: utf-8 -*-
"""matplotlib.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cOUB81uHmDbAWbU856IP0-cdWI1UrA_M
"""

pip install matplotlib

import matplotlib.pyplot as plt
import numpy as np

from google.colab.patches import cv2_imshow
import cv2
rasm = cv2.imread('/content/7. Бабочка.jpg')
cv2_imshow(rasm)

yorqinlik = cv2.GaussianBlur(rasm,(7,7),5)
cv2_imshow(yorqinlik)

oqqora = cv2.cvtColor(yorqinlik,cv2.COLOR_BGR2GRAY)
cv2_imshow(oqqora)



